---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# The Python Programming Language: Functions

In [ ]:
x = 1
y = 2
x + y

In [ ]:
x

<br>
`add_numbers` is a function that takes two numbers and adds them together.

In [ ]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

<br>
`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [ ]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

<br>
`add_numbers` updated to take an optional flag parameter.

In [ ]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

<br>
Assign function `add_numbers` to variable `a`.

In [ ]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)

<br>
# The Python Programming Language: Types and Sequences

<br>
Use `type` to return the object's type.

In [ ]:
type('This is a string')

In [ ]:
type(None)

In [ ]:
type(1)

In [ ]:
type(1.0)

In [ ]:
type(add_numbers)

<br>
Tuples are an immutable data structure (cannot be altered).

In [ ]:
x = (1, 'a', 2, 'b')
type(x)

<br>
Lists are a mutable data structure.

In [ ]:
x = [1, 'a', 2, 'b']
type(x)

<br>
Use `append` to append an object to a list.

In [ ]:
x.append(3.3)
print(x)

<br>
This is an example of how to loop through each item in the list.

In [ ]:
for item in x:
    print(item)

<br>
Or using the indexing operator:

In [ ]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

<br>
Use `+` to concatenate lists.

In [ ]:
[1,2] + [3,4]

<br>
Use `*` to repeat lists.

In [ ]:
[1]*3

<br>
Use the `in` operator to check if something is inside a list.

In [ ]:
1 in [1, 2, 3]

<br>
Now let's look at strings. Use bracket notation to slice a string.

In [ ]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters


<br>
This will return the last element of the string.

In [ ]:
x[-1]

<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [ ]:
x[-4:-2]

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [ ]:
x[:3]

<br>
And this is a slice starting from the 3rd element of the string and going all the way to the end.

In [ ]:
x[3:]

In [ ]:
firstname = 'Christopher'
lastname = 'Brooks'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Chris' in firstname)


<br>
`split` returns a list of all the words in a string, or a list split on a specific character.

In [ ]:
firstname = 'Christopher Arthur Hansen Brooks'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Christopher Arthur Hansen Brooks'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

<br>
Make sure you convert objects to strings before concatenating.

In [ ]:
'Chris' + 2

In [ ]:
'Chris' + str(2)

<br>
Dictionaries associate keys with values.

In [ ]:
x = {'Christopher Brooks': 'brooksch@umich.edu', 'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


In [ ]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

<br>
Iterate over all of the keys:

In [ ]:
for name in x:
    print(x[name])

<br>
Iterate over all of the values:

In [ ]:
for email in x.values():
    print(email)

<br>
Iterate over all of the items in the list:

In [ ]:
for name, email in x.items():
    print(name)
    print(email)

<br>
You can unpack a sequence into different variables:

In [ ]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [ ]:
fname

In [ ]:
lname

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [ ]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email = x

<br>
# The Python Programming Language: More on Strings

In [ ]:
print('Chris' + 2)

In [ ]:
print('Chris' + str(2))

<br>
Python has a built in method for convenient string formatting.

In [ ]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


<br>
# Reading and Writing CSV files

<br>
Let's import our datafile mpg.csv, which contains fuel economy data for 234 cars.

* mpg : miles per gallon
* class : car classification
* cty : city mpg
* cyl : # of cylinders
* displ : engine displacement in liters
* drv : f = front-wheel drive, r = rear wheel drive, 4 = 4wd
* fl : fuel (e = ethanol E85, d = diesel, r = regular, p = premium, c = CNG)
* hwy : highway mpg
* manufacturer : automobile manufacturer
* model : model of car
* trans : type of transmission
* year : model year

In [ ]:
import csv

%precision 2

with open('mpg.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))
    
mpg[:3] # The first three dictionaries in our list.

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 234 dictionaries.

In [ ]:
len(mpg)

<br>
`keys` gives us the column names of our csv.

In [ ]:
mpg[0].keys()

<br>
This is how to find the average cty fuel economy across all cars. All values in the dictionaries are strings, so we need to convert to float.

In [ ]:
sum(float(d['cty']) for d in mpg) / len(mpg)

<br>
Similarly this is how to find the average hwy fuel economy across all cars.

In [ ]:
sum(float(d['hwy']) for d in mpg) / len(mpg)

<br>
Use `set` to return the unique values for the number of cylinders the cars in our dataset have.

In [ ]:
cylinders = set(d['cyl'] for d in mpg)
cylinders

<br>
Here's a more complex example where we are grouping the cars by number of cylinder, and finding the average cty mpg for each group.

In [ ]:
CtyMpgByCyl = []

for c in cylinders: # iterate over all the cylinder levels
    summpg = 0
    cyltypecount = 0
    for d in mpg: # iterate over all dictionaries
        if d['cyl'] == c: # if the cylinder level type matches,
            summpg += float(d['cty']) # add the cty mpg
            cyltypecount += 1 # increment the count
    CtyMpgByCyl.append((c, summpg / cyltypecount)) # append the tuple ('cylinder', 'avg mpg')

CtyMpgByCyl.sort(key=lambda x: x[0])
CtyMpgByCyl

<br>
Use `set` to return the unique values for the class types in our dataset.

In [ ]:
vehicleclass = set(d['class'] for d in mpg) # what are the class types
vehicleclass

<br>
And here's an example of how to find the average hwy mpg for each class of vehicle in our dataset.

In [ ]:
HwyMpgByClass = []

for t in vehicleclass: # iterate over all the vehicle classes
    summpg = 0
    vclasscount = 0
    for d in mpg: # iterate over all dictionaries
        if d['class'] == t: # if the cylinder amount type matches,
            summpg += float(d['hwy']) # add the hwy mpg
            vclasscount += 1 # increment the count
    HwyMpgByClass.append((t, summpg / vclasscount)) # append the tuple ('class', 'avg mpg')

HwyMpgByClass.sort(key=lambda x: x[1])
HwyMpgByClass

<br>
# The Python Programming Language: Dates and Times

In [ ]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [ ]:
tm.time()

<br>
Convert the timestamp to datetime.

In [ ]:
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

<br>
Handy datetime attributes:

In [ ]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

<br>
`timedelta` is a duration expressing the difference between two dates.

In [ ]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

<br>
`date.today` returns the current local date.

In [ ]:
today = dt.date.today()

In [ ]:
today - delta # the date 100 days ago

In [ ]:
today > today-delta # compare dates

<br>
# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

In [ ]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [ ]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

<br>
Here's an example of mapping the `min` function between two lists.

In [ ]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

<br>
Now let's iterate through the map object to see the values.

In [ ]:
for item in cheapest:
    print(item)

<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [ ]:
my_function = lambda a, b, c : a + b

In [ ]:
my_function(1, 2, 3)

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [ ]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

<br>
Now the same thing but with list comprehension.

In [ ]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [1]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [2]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [3]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [4]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [5]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [26]:
n = np.arange(2000,2017) # start at 0 count up by 2, stop before 30
n

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010,
       2011, 2012, 2013, 2014, 2015, 2016])

In [22]:
import pandas as pd
cols = pd.date_range('2000-01', '2001-12', freq='MS')
cols = cols.strftime('%Y-%m')
df = pd.DataFrame(np.random.randn(10, 24), columns=cols)
df

2000-01   2000-02   2000-03   2000-04   2000-05   2000-06   2000-07  \
0 -0.046590  0.239351  1.178045 -1.253888  0.957278  1.301667  1.242401   
1  0.068633 -0.192966 -0.710361  0.173139  0.929926  1.664442  0.988829   
2 -0.006129 -1.180507  0.052041  0.093442  1.489294  0.808208  0.960273   
3 -0.573999 -0.019657  0.231156  0.181986  2.018643 -0.192414  0.741764   
4 -1.821320 -0.932111 -2.407826 -0.006285  1.051021 -0.362889  1.014265   
5  0.189984 -0.821714  0.086780  0.732883 -0.241415 -1.812670 -1.740893   
6  0.797179  0.516974 -1.491769  0.953895  1.567398 -0.547556 -0.917966   
7 -0.356857 -1.065038  0.948408  0.520929  0.998816 -0.412255  1.129410   
8  0.452198  0.018952  0.089549  1.827693 -0.731430 -0.049808  1.132996   
9 -0.689848  0.216905 -1.958143 -0.008026  0.662375  0.155471 -1.033988   

    2000-08   2000-09   2000-10    ...      2001-03   2001-04   2001-05  \
0 -0.940218 -0.670078 -0.983381    ...     1.274346 -0.893197 -1.419602   
1  0.379652  0.173600  1.348970    ...    -0.780017 -0.838021 -3.271677   
2 -0.895338 -0.757321  0.838414    ...    -0.420642  1.465850  0.123829   
3  0.916398 -0.208836  0.682672    ...    -0.668906  0.024560 -0.786591   
4 -0.772995  0.380183 -0.856951    ...     0.005362  0.787147  1.067532   
5  0.698091 -1.199311 -1.790687    ...     0.604010 -1.863808 -0.605664   
6 -2.196754 -0.109995  0.119716    ...    -0.191736  0.647032  0.944498   
7  0.467201 -0.658277 -1.546196    ...    -0.715756 -0.302425  0.668883   
8 -0.021175  0.047749 -1.688774    ...     0.174579  0.787842 -2.403809   
9  0.810971  0.346193 -0.246274    ...    -0.767121 -0.665183 -0.766761   

    2001-06   2001-07   2001-08   2001-09   2001-10   2001-11   2001-12  
0 -0.807704  0.630163 -1.289219 -0.811195  1.134496 -0.914505 -0.622891  
1  0.093686 -0.674648  0.200576 -0.148439 -0.572545  0.170882 -0.659977  
2  0.046096 -2.094164  1.505808 -0.835245 -0.524769  0.822394  1.389365  
3 -1.755905 -0.719258  0.454416 -0.842312  0.556063  0.417901 -0.920672  
4  0.642906  0.432855  2.141952 -0.681273 -1.774524 -0.224377 -0.266320  
5  0.395792 -0.239979  0.170026  0.303427 -1.954415 -0.364311 -0.751727  
6  1.721875 -0.119700  1.121713 -0.149831  0.772123  0.161664  0.678178  
7  0.544943 -0.957619 -0.470716 -0.252684 -0.582499 -1.655056  0.026712  
8  1.212770  0.721579  0.934267 -1.438564  1.353527 -0.626570 -0.182014  
9  0.883663  0.167273 -0.145552  0.445324 -0.981752  0.706542  1.276851  

[10 rows x 24 columns]

In [23]:
df.columns

Index(['2000-01', '2000-02', '2000-03', '2000-04', '2000-05', '2000-06',
       '2000-07', '2000-08', '2000-09', '2000-10', '2000-11', '2000-12',
       '2001-01', '2001-02', '2001-03', '2001-04', '2001-05', '2001-06',
       '2001-07', '2001-08', '2001-09', '2001-10', '2001-11', '2001-12'],
      dtype='object')

In [25]:
np.arange(len(df.columns))//3

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7,
       7])

In [12]:
df = df.groupby(np.arange(len(df.columns))//3, axis=1).mean()
df

0         1
0 -0.440477  0.512729
1 -0.318237  1.474290
2 -1.279557 -1.050822
3  0.652054 -0.432481
4  0.213990 -0.142170
5 -1.120870  0.744639
6 -0.553308  0.331486
7  0.484245 -0.600659
8 -0.137859  1.422050
9 -0.193387  0.087269

<br>
`reshape` returns an array with the same data with a new shape.

In [7]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [ ]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

<br>
`resize` changes the shape and size of array in-place.

In [ ]:
o.resize(3, 3)
o

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [ ]:
np.ones((3, 2))

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [ ]:
np.zeros((2, 3))

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [ ]:
np.eye(3)

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [ ]:
np.diag(y)

<br>
Create an array using repeating list (or see `np.tile`)

In [ ]:
np.array([1, 2, 3] * 3)

<br>
Repeat elements of an array using `repeat`.

In [ ]:
np.repeat([1, 2, 3], 3)

<br>
#### Combining Arrays

In [ ]:
p = np.ones([2, 3], int)
p

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [ ]:
np.vstack([p, 2*p])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [ ]:
np.hstack([p, 2*p])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [ ]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

In [ ]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

In [ ]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [ ]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

In [ ]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [ ]:
z = np.array([y, y**2])
z

<br>
The shape of array `z` is `(2,3)` before transposing.

In [ ]:
z.shape

<br>
Use `.T` to get the transpose.

In [ ]:
z.T

<br>
The number of rows has swapped with the number of columns.

In [ ]:
z.T.shape

<br>
Use `.dtype` to see the data type of the elements in the array.

In [ ]:
z.dtype

<br>
Use `.astype` to cast to a specific type.

In [ ]:
z = z.astype('f')
z.dtype

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [ ]:
a = np.array([-4, -2, 1, 3, 5])

In [ ]:
a.sum()

In [ ]:
a.max()

In [ ]:
a.min()

In [ ]:
a.mean()

In [ ]:
a.std()

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [ ]:
a.argmax()

In [ ]:
a.argmin()

<br>
## Indexing / Slicing

In [ ]:
s = np.arange(13)**2
s

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [ ]:
s[0], s[4], s[-1]

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [ ]:
s[1:5]

<br>
Use negatives to count from the back.

In [ ]:
s[-4:]

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [ ]:
s[-5::-2]

<br>
Let's look at a multidimensional array.

In [ ]:
r = np.arange(36)
r.resize((6, 6))
r

<br>
Use bracket notation to slice: `array[row, column]`

In [ ]:
r[2, 2]

<br>
And use : to select a range of rows or columns

In [ ]:
r[3, 3:6]

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [ ]:
r[:2, :-1]

<br>
This is a slice of the last row, and only every other element.

In [ ]:
r[-1, ::2]

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [ ]:
r[r > 30]

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [ ]:
r[r > 30] = 30
r

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [ ]:
r2 = r[:3,:3]
r2

<br>
Set this slice's values to zero ([:] selects the entire array)

In [ ]:
r2[:] = 0
r2

<br>
`r` has also been changed!

In [ ]:
r

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [ ]:
r_copy = r.copy()
r_copy

<br>
Now when r_copy is modified, r will not be changed.

In [ ]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [ ]:
test = np.random.randint(0, 10, (4,3))
test

<br>
Iterate by row:

In [ ]:
for row in test:
    print(row)

<br>
Iterate by index:

In [ ]:
for i in range(len(test)):
    print(test[i])

<br>
Iterate by row and index:

In [ ]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

<br>
Use `zip` to iterate over multiple iterables.

In [ ]:
test2 = test**2
test2

In [ ]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)